### ISSUE TITLE
getting a nill value global multiplier line 299

### ISSUE THREAD

**Issue by toddy617** [Rez855/TunerChip#1]
dunno why its doing did try and have a play but could not sort wondered if you could hellp please
![Screenshot_90](https://user-images.githubusercontent.com/56977922/80833896-7ed7ce80-8be7-11ea-862f-9efea45a4ca2.png)

**Comment by Rez855** [comment]
I committed a change that should hopefully fix this issue. I don't have a server setup currently so I can't test it. Just let me know if its still broken.
